[package]
name = "pdr-rust-sdk"
version = "0.1.0"
authors = ["wangyan <wyanlord@sina.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
